"""
industry_config.py — Industry-specific configuration for the Prospect Analyzer.

Customize this file to change what the agent analyzes and how reports are branded.
See the examples at the bottom for different industry configurations.
"""

import os

# === Analysis Configuration ===

# Agent name (used in Anthropic Managed Agents API)
AGENT_NAME = os.getenv("AGENT_NAME", "prospect-analyzer")

# Company name for HTML report branding
COMPANY_NAME = os.getenv("COMPANY_NAME", "Prospect Analyzer")

# System prompt that defines what the agent analyzes
# This is the core of the analysis — change it to analyze any industry
SYSTEM_PROMPT = os.getenv("ANALYSIS_SYSTEM_PROMPT", """You are an expert analyst who evaluates businesses based on their web presence.

Your task:
1. Visit the given website URL and explore their products/services.
2. Identify: brand name, product types, pricing range, number of products/services.
3. Analyze readiness for industry compliance requirements.

Output a structured analysis (~1 page):

# Analysis: [Brand Name]

## 1. Brand Profile
(name, website, segment, pricing range, number of products)

## 2. Product/Service Portfolio
(types, main categories, key offerings)

## 3. Current Data Status
(what information the brand already provides on their website)

## 4. Gap Analysis
(what's missing for compliance — checklist table)

## 5. Recommendations
(specific steps, prioritized by difficulty)

## 6. Summary
(overall readiness score 1-10, main risks, estimated implementation effort)

Use data directly from the website. Be specific — cite examples.""")

# User message template — {url} will be replaced with the target URL
USER_MESSAGE_TEMPLATE = os.getenv("ANALYSIS_USER_MESSAGE", (
    "Analyze this website: {url}\n\n"
    "Browse the site, look at product/service pages, identify key information.\n\n"
    "Then create a complete readiness analysis."
))

# Session title template — {domain} will be replaced with the target domain
SESSION_TITLE_TEMPLATE = "Analysis: {domain}"

# === HTML Report Configuration ===

# Report title pattern (used in HTML <title> and header)
REPORT_TITLE_TEMPLATE = "Analysis — {brand}"

# Report header tag line
REPORT_HEADER_TAG = "Readiness Analysis"

# Report score label
REPORT_SCORE_LABEL = "Readiness"

# Report subtitle
REPORT_SUBTITLE = "Compliance readiness assessment"

# Report footer text
REPORT_FOOTER = "Generated by {company_name}"

# Deploy file suffix (appended to domain slug)
DEPLOY_FILE_SUFFIX = "-analysis"

# === Markdown Parsing ===

# Regex to extract brand name from analysis markdown
# Default: looks for "# Analysis: Brand Name"
BRAND_REGEX = r"^#\s+(?:Analysis|Report):\s*(.+)$"

# Regex to extract readiness score from analysis markdown
# Default: looks for "Readiness score: X/10" or similar
SCORE_REGEX = r"(?:Readiness|Score)[:\s]+\*?\*?(\d+[\.,]?\d*)\s*/\s*10"


# ============================================================
# EXAMPLES — Uncomment one of these blocks to use a preset
# ============================================================

# --- Example: DPP/Textile Industry (ESPR compliance) ---
# SYSTEM_PROMPT = """You are an expert on Digital Product Passports (DPP)
# under the ESPR regulation for the textile industry...
# [full prompt for textile/fashion DPP analysis]"""
# USER_MESSAGE_TEMPLATE = "Analyze this fashion e-shop for DPP readiness: {url}"
# REPORT_HEADER_TAG = "DPP Readiness Analysis"
# BRAND_REGEX = r"^#\s+DPP Analysis:\s*(.+)$"
# SCORE_REGEX = r"DPP Readiness[:\s]+\*?\*?(\d+[\.,]?\d*)\s*/\s*10"

# --- Example: SaaS Security Audit ---
# SYSTEM_PROMPT = """You are a cybersecurity expert evaluating SaaS products
# for SOC 2 / ISO 27001 compliance readiness...
# [full prompt for security audit]"""
# USER_MESSAGE_TEMPLATE = "Evaluate this SaaS product for security compliance: {url}"
# REPORT_HEADER_TAG = "Security Readiness Assessment"

# --- Example: E-commerce UX Audit ---
# SYSTEM_PROMPT = """You are a UX/conversion expert who analyzes e-commerce
# stores for usability, performance, and conversion optimization...
# [full prompt for UX audit]"""
# USER_MESSAGE_TEMPLATE = "Analyze this e-commerce store's UX and conversion readiness: {url}"
# REPORT_HEADER_TAG = "UX & Conversion Assessment"
